spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  OAuth2:
    google:
      url: https://accounts.google.com/o/oauth2/v2/auth
      client-id: 798939476338-svr466e3go6p31tme7lom2jm30pc6ka5.apps.googleusercontent.com
      client-secret: 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
      callback-login-url: http://localhost:8080/app/users/auth/google/login/callback # 등록한 정보에 맞게 수정해주세요
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile # 등록한 정보에 맞게 수정해주세요
    kakao:
      url: https://kauth.kakao.com/oauth/authorize
      client-id: cbc0ebaf357f93886ab19b67c4e578b1
      client-secret:
      callback-login-url: http://localhost:8080/app/users/auth/kakao/login/callback
      scope: profile_nickname, account_email

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret-key: UwKYibQQgkW7gkap9kjewxBHb9wdXoBT4vnt4P3sJWtNu  # JWT key. 수정해주세요


